apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: infra-crowdsec-pvc
  namespace: crowdsec
  labels:
    app.kubernetes.io/name: crowdsec
    app.kubernetes.io/part-of: infra
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: oci-bv
  resources:
    requests:
      storage: 50Gi